#!/bin/bash

CC=/opt/homebrew/opt/llvm/bin/clang++
LINK=/opt/homebrew/opt/llvm/bin/clang++
MOC=/opt/homebrew/Cellar/qt@5/5.15.12/bin/moc
COMPILE_FLAGS="-I/opt/homebrew/Cellar/qt@5/5.15.12/lib/QtGui.framework/Headers \
  -I/opt/homebrew/Cellar/qt@5/5.15.12/lib/QtCore.framework/Headers \
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers \
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/AGL.framework/Headers \
  -I/opt/homebrew/Cellar/qt@5/5.15.12/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.12/lib"
LINK_FLAGS="-F/opt/homebrew/Cellar/qt@5/5.15.12/lib -framework QtGui -framework AppKit -framework Metal \
  -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL"

$CC -c -std=c++17 -fPIC $COMPILE_FLAGS -o openglwindow.o openglwindow.cpp

$CC -c -std=c++17 -fPIC $COMPILE_FLAGS -o main.o main.cpp

$CC -std=c++17 -dM -E -o moc_predefs.h /opt/homebrew/Cellar/qt@5/5.15.12/mkspecs/features/data/dummy.cpp

$MOC --include /Users/jason/cs/side-projects/experiments/qt-opengl/moc_predefs.h \
  -I/opt/homebrew/Cellar/qt@5/5.15.12/mkspecs/macx-clang -I/Users/jason/cs/side-projects/experiments/qt-opengl \
  -I/Users/jason/cs/side-projects/experiments/qt-opengl -I/opt/homebrew/Cellar/qt@5/5.15.12/lib/QtGui.framework/Headers \
  -I/opt/homebrew/Cellar/qt@5/5.15.12/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1 \
  -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include \
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include \
  -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.12/lib \
  openglwindow.h -o moc_openglwindow.cpp

$CC -c -std=c++17 -fPIC $COMPILE_FLAGS -o moc_openglwindow.o moc_openglwindow.cpp

$LINK $LINK_FLAGS -o openglwindow.app/Contents/MacOS/openglwindow openglwindow.o main.o moc_openglwindow.o
