#!/bin/bash

CC=/opt/homebrew/opt/llvm/bin/clang++
LINK=/opt/homebrew/opt/llvm/bin/clang++
MOC=/opt/homebrew/Cellar/qt@5/5.15.12/bin/moc
COMPILE_FLAGS="-std=c++17 -fPIC -I/opt/homebrew/Cellar/qt@5/5.15.12/lib/QtGui.framework/Headers \
  -I/opt/homebrew/Cellar/qt@5/5.15.12/lib/QtCore.framework/Headers \
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers \
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/AGL.framework/Headers \
  -I/opt/homebrew/Cellar/qt@5/5.15.12/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.12/lib"
LINK_FLAGS="-F/opt/homebrew/Cellar/qt@5/5.15.12/lib -framework QtGui -framework AppKit -framework Metal \
  -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL"

$CC -c $COMPILE_FLAGS -o openglwindow.o openglwindow.cpp

$CC -c $COMPILE_FLAGS -o main.o main.cpp

$MOC -o moc_openglwindow.cpp openglwindow.h

$CC -c $COMPILE_FLAGS -o moc_openglwindow.o moc_openglwindow.cpp

$LINK $LINK_FLAGS -o openglwindow.app/Contents/MacOS/openglwindow openglwindow.o main.o moc_openglwindow.o

rm moc_openglwindow.cpp
rm *.o
